### PR TITLE
Configure renovate to issue dependency updates to both main and v7.

### PR DESCRIPTION
**Pull request by tjololo**
## Description
As we need to keep supporting v7 we should enable renovate on the v7-branch as well.

## Related Issue(s)
N/A

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

### CODE REVIEW

**Review by ivarne — APPROVED** [review]

**Comment by ivarne** [comment]
This will need to be applied to v7 also?

**Comment by tjololo** [comment]
No, I believe renovate fetches its config from main

**Comment by ivarne** [comment]
In that case I would expect renovate to create pull requests on v7

**Comment by tjololo** [comment]
Renovate is limiting the number of open PRs to not flood the list. This issue contains all the scheduled updates: https://github.com/Altinn/app-lib-dotnet/issues/31
v7 is present so the config should be good

**Pull request merged**
