### PR TITLE
Fix issue where datamodel decimal properties are stored with greater precision than is supported by frontend

### PR DESCRIPTION
**Pull request by martinothamar**
## Description
Suggested fix for resolving issues around decimal precisions across systems

A datamodel generated by Studio might look like this:
image

In some cases, apps have calculated fields that are decimal, which can lead to a lot of precision being used.
When this data is stored, all 128bits of `decimal` precision come with, but the frontend which lives in JS land
will only have 64bit numbers. So when data is posted back (for whatever reason, maybe they shouldn't in this scenario), the `test` JSON patch operation will fail because the field has higher precision coming from storage than it has from the client request.

Alternatives
* Keep storing 128bit precision, but make JSON patch more tolerant instead (comparison based on double precision)
* Don't allow decimal properties in datamodels
* ???

## Related Issue(s)
- https://github.com/Altinn/app-frontend-react/issues/2066

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

### CODE REVIEW

**Comment by martinothamar** [comment]
@nkylstad @mirkoSekulic do you have any input or ideas on this?

**Comment by ivarne** [comment]
Tried my luck at writing some tests, and obviously found a few issues and previous errors and locations for improved comments.

1. The same problem with rounding in javascript happens to `long` so I included it as well.
2. This is fixing a Json problem, so we should not round properties with `[JsonIgnore]`

```c#
public string StringBackingField { get; set; }

[JsonIgnore]
public decimal DecimalView { get { decimal.Parse(StringBackingField )} set {StringBackingField = value.ToString()} }

```

**Comment by ivarne** [comment]
@martinothamar I don't love this solution, but it does solve some very real problems that likely won't ever go away for existing apps. Can you add a comment with the justification for not doing this?

**Comment by martinothamar** [comment]
Conclusion was posted in: https://github.com/Altinn/app-frontend-react/issues/2066#issuecomment-2161140745
Solution being updated docs, and not special casing large numeric types, that was my interpretation anyway

**Pull request closed without merging**
