### PR TITLE
Add JsonEquivilentTo extension for FluentAssertions

### PR DESCRIPTION
**Pull request by ivarne**
See https://github.com/fluentassertions/fluentassertions/pull/2493

This greatly simplifies writing tests that ensure that a json response is the same as another without carefully ensuring that spaces are the same.

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

### CODE REVIEW

**Comment by ivarne** [comment]
Hurra for tidssoner. Testene funker lokalt i GMT+1, men feiler i CI fordi de bruker GMT+0. Funket tidligere fordi vi deserialiserte til C# klasser og Equivalent sammenligner tidssone konvertering. Synes egentlig koden vår burde være stabil for tidssone, men det er vel litt utenfor scope nå.

**Comment by tjololo** [comment]
I see the nice ness of the `BeJsonEquivalentTo` comparator, but not sure if this is the correct way. I would much rather leave our test as they are focus on providing an solution upstream to fluentassertion and wait for it to come as a part of the library.

If we choose to create a new nuget with altinn test utils I would rather have it in a separate repository. That way we can leverage github releases and have a cleaner way of releasing and sharing the testutils with the whole organisation and others.

At the same time as I'm writing this the change of these test I think exposed a mistake in our codebase, doing a quick search in the code I see that we in most cases use DateTime.UtcNow, but two places (excluding logging/console.write) we use DateTime.Now. Have created an isse #382 for further discussions on the timezone issue (as that seems to be out of scope for this PR as you say)

**Comment by ivarne** [comment]
This was not intended to only fix this test, but something I'd like to be able to do for other tests as well. It is obviously a separate issue, so I just used it in an existing test for illustration. The fact that it caught an issue is in my opinion a validation of the testing approach.

>  I would much rather leave our test as they are focus on providing an solution upstream to fluentassertion and wait for it to come as a part of the library.

If I'm to try to contribute this functionality to fluentassertions, I probably need some exprience catching issues like this to help advocate for the change.

> If we choose to create a new nuget with altinn test utils I would rather have it in a separate repository. That way we can leverage github releases and have a cleaner way of releasing and sharing the testutils with the whole organisation and others.

Yes, If we find this useful to share and fluentassertions does not merge it in properly soon, we should probably maintain it as a separate git repo and nugget package. I don't see why we can't develop and catch issues here first. Versioning cross repo is not fun while developing this as a side project.

**Comment by tjololo** [comment]
Not sure if the timezone difference  an actual bug, more of a codesmell, we should look into catching this with a linter/static code analysis tool. 
We should definitely fix it, but if the api consumer does not handle timezones thats a bug on their end IMO. We should strive to make it easier for the consumer, but timezones and the timeformat defining the timezone is there for a reason.
Unless it is necessary to have this functionality for delivering the functionality we have commited to this and the upcoming sprints I think we should hold back on this until those are delivered and see how the PR against fluentassertions progresses while we work on delivering the functionality to our users

**Comment by ivarne** [comment]
> Not sure if the timezone difference an actual bug, more of a codesmell, we should look into catching this with a linter/static code analysis tool.

I'm not sure it is a bug in the code either. The main issue is that our test did not catch that the output isn't stable between systems.

**Pull request closed without merging**
