### PR TITLE
Rename the ?lang= parameter in process/next to ?language

### PR DESCRIPTION
**Pull request by ivarne**
This is to match other endpoints and make a more uniform api

Obviously while keeping backwards compatibility

## Related Issue(s)
- https://github.com/Altinn/app-frontend-react/issues/1774

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

### CODE REVIEW

**Comment by tjololo** [comment]
How should we label this so it's clearly marked in the release notes? It's not a breaking change since we support the old param, but we should notify other api consumers that are potentially using this that the param has changed from `lang` to `language` and that we are deprecating the `lang` param, if that is what we are doing?

**Comment by ivarne** [comment]
> How should we label this so it's clearly marked in the release notes? It's not a breaking change since we support the old param, but we should notify other api consumers that are potentially using this that the param has changed from lang to language and that we are deprecating the lang param, if that is what we are doing?

Yes, that is what I was doing. I initially thought this was only for our code, but obviously someone might have used `IHttpContextFactory` to get this value in one of the interface hooks. It seems far fetched, but might be possible. Maybe just search all repos to see if someone has used it?

**Comment by tjololo** [comment]
> Yes, that is what I was doing. I initially thought this was only for our code, but obviously someone might have used `IHttpContextFactory` to get this value in one of the interface hooks. It seems far fetched, but might be possible. Maybe just search all repos to see if someone has used it?

I did a quick search in studio through giteas explore mode for "lang" can't see any C# code that are accessing the `IHttpContextFactory` to extract `lang` any where. Another factor is the consumers of the apps api, some applications are not tied to our frontend but used directly through the API. When a ServiceOwner upgrades his application to v8 we need to tell that consumers of the API should use `language` instead of `lang` when they call process/next, if they are using it.
This will then give them a "grace"-period where both work and the can migrate their solutions using the apps API

**Comment by ivarne** [comment]
> This will then give them a "grace"-period where both work and the can migrate their solutions using the apps API

Hmm... This PR only makes both versions work for pdf language, not potential future usages like other process tasks. Do you think I should add compatibility on the controller as well? It seems kind of strange as it isn't used right now, but would be a sign for the future that clients might set `lang` instead of `language`

**Comment by tjololo** [comment]
No didn't mean we should add it to the controller, just that we need to inform the app developers that they need to inform their api consumers about this change

**Review by tjololo — APPROVED** [review]
We should document this in the changelog and release notes. I agree that we should use the same param name in all api endpoint

**Review by RonnyB71 — APPROVED** [review]
🕹️

**Pull request merged**
