### PR TITLE
Use presence of org in user claims for conditionally setting read status on instance create

### PR DESCRIPTION
**Pull request by chrrust**
## Description
Uses the presence of org in user claim to conditionally set created instance to read or unread. The problem this tries to solve is when the instance is created by a different org than owns the instance. This is the case for Digital Gravferdsmelding. This project uses Digdir as Maskinporten-tenant, but the apps are owned by Statsforvalteren i Vestfold og Telemark (sfvt).

## Related Issue(s)
N/A

## Verification
- [x] **Your** code builds clean without any errors or warnings
- [x] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [x] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

### CODE REVIEW

**Review by ivarne — APPROVED** [review]
Looks good to me.

This is just about the read status, and the access for cross service owner writes is still regulated by policy.xml

**Review by martinothamar — COMMENTED** [review]
Hmmm I'm not sure I'm comfortable with a behavior change like this. I don't know that no one else relies on the current behavior (or will have their internal workflow impacted in some way)

**Comment by ivarne** [comment]
This is just about the read status of the instance (as shown in Altinn inbox). As long as it is an api call with a service owner token, it should never be marked as read.

**Comment by chrrust** [comment]
Any updates on the review of this?

**Pull request merged**
